### ISSUE TITLE
RAML1.0: ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by jans23** [raml2html/raml2html#221]
I installed the raml1.0 branch with  `sudo npm i -g git+https://git@github.com/raml2html/raml2html.git\#raml1.0` which seemed to work.

When executing raml2html I retrieve the following error:

```
 /usr/local/lib/node_modules/raml2html/node_modules/raml2obj/node_modules/raml-1-parser/dist/raml1/jsyaml/jsyaml2lowLevel.js:498
        return new Promise(function (resolve, reject) {
                   ^
ReferenceError: Promise is not defined
    at FSResolverImpl.contentAsync (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/node_modules/raml-1-parser/dist/raml1/jsyaml/jsyaml2lowLevel.js:498:20)
    at Project.unitAsync (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/node_modules/raml-1-parser/dist/raml1/jsyaml/jsyaml2lowLevel.js:938:37)
    at Object.fetchIncludesAndMasterAsync (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/node_modules/raml-1-parser/dist/raml1/jsyaml/jsyaml2lowLevel.js:3384:20)
    at fetchAndLoadApiAsync (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/node_modules/raml-1-parser/dist/raml1/apiLoader.js:179:19)
    at loadRAMLAsync (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/node_modules/raml-1-parser/dist/raml1/apiLoader.js:123:16)
    at Object.loadApiAsync (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/node_modules/raml-1-parser/dist/raml1/apiLoader.js:94:23)
    at Object.loadApi (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/node_modules/raml-1-parser/dist/index.js:71:22)
    at _sourceToRamlObj (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/index.js:87:19)
    at Object.parse (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/index.js:108:10)
    at Object.render (/usr/local/lib/node_modules/raml2html/index.js:23:19)
```
Am I doing something wrong? In case my spec not accurate I would like to change it but would need to understand which aspect to change.

My system:
* Debian Linux Jessie
* node v0.10.25
* npm 1.3.10

**Comment by jensklose** [comment]
Your node version is to low.
Native Promise support starts with 0.12., see [NodeJS doc](https://nodejs.org/docs/v0.1.12/api.html#_tt_node_promise_tt)

**Comment by kevinrenskers** [comment]
The upcoming raml2html 3.0.0 will require Node 4 or higher. The current raml2html 2.5.0 should be good on older versions.
