### ISSUE TITLE
develop: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by chulkilee** [raml2html/raml2html#249]
```
npm version
{ raml2html: '3.0.0-beta1',
  npm: '3.10.5',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.3.1',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.57',
  zlib: '1.2.8' }
```

```
node --version
v6.3.1
```

```
git rev-parse HEAD
2f5f7b25ddb404cea79d1c991a19d9a27a56f0a2
```

```
bin/raml2html examples/github.raml
Error: TypeError: Cannot read property 'forEach' of undefined
    at /src/raml2html/bin/raml2html:40:17
    at _rejected (/src/raml2html/node_modules/q/q.js:808:24)
    at /src/raml2html/node_modules/q/q.js:834:30
    at Promise.when (/src/raml2html/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/src/raml2html/node_modules/q/q.js:752:41)
    at /src/raml2html/node_modules/q/q.js:574:44
    at flush (/src/raml2html/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

```
npm list
raml2html@3.0.0-beta1 /src/raml2html
├─┬ commander@2.9.0
│ └── graceful-readlink@1.0.1
├─┬ eslint@3.2.2
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├── has-ansi@2.0.0
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ ├─┬ concat-stream@1.5.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ readable-stream@2.0.6
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── process-nextick-args@1.0.7
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ └── typedarray@0.0.6
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├─┬ doctrine@1.2.2
│ │ ├── esutils@1.1.6
│ │ └── isarray@1.0.0
│ ├─┬ escope@3.6.0
│ │ ├─┬ es6-map@0.1.4
│ │ │ ├── es6-set@0.1.4
│ │ │ ├── es6-symbol@3.1.0
│ │ │ └── event-emitter@0.3.4
│ │ ├── es6-weak-map@2.0.1
│ │ └─┬ esrecurse@4.1.0
│ │   └── estraverse@4.1.1
│ ├─┬ espree@3.1.7
│ │ ├── acorn@3.3.0
│ │ └── acorn-jsx@3.0.1
│ ├── estraverse@4.2.0
│ ├── esutils@2.0.2
│ ├─┬ file-entry-cache@1.3.1
│ │ ├─┬ flat-cache@1.2.1
│ │ │ ├── circular-json@0.3.1
│ │ │ ├─┬ del@2.2.1
│ │ │ │ ├─┬ globby@5.0.0
│ │ │ │ │ └─┬ array-union@1.0.2
│ │ │ │ │   └── array-uniq@1.0.3
│ │ │ │ ├── is-path-cwd@1.0.0
│ │ │ │ ├─┬ is-path-in-cwd@1.0.0
│ │ │ │ │ └── is-path-inside@1.0.0
│ │ │ │ ├── pify@2.3.0
│ │ │ │ ├─┬ pinkie-promise@2.0.1
│ │ │ │ │ └── pinkie@2.0.4
│ │ │ │ └── rimraf@2.5.4
│ │ │ ├── graceful-fs@4.1.5
│ │ │ └── write@0.2.1
│ │ └── object-assign@4.1.0
│ ├─┬ glob@7.0.5
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.5
│ │ │ └── wrappy@1.0.2
│ │ ├─┬ minimatch@3.0.3
│ │ │ └─┬ brace-expansion@1.1.6
│ │ │   ├── balanced-match@0.4.2
│ │ │   └── concat-map@0.0.1
│ │ ├── once@1.3.3
│ │ └── path-is-absolute@1.0.0
│ ├── globals@9.9.0
│ ├── ignore@3.1.3
│ ├── imurmurhash@0.1.4
│ ├─┬ inquirer@0.12.0
│ │ ├── ansi-escapes@1.4.0
│ │ ├── ansi-regex@2.0.0
│ │ ├─┬ cli-cursor@1.0.2
│ │ │ └─┬ restore-cursor@1.0.1
│ │ │   ├── exit-hook@1.1.1
│ │ │   └── onetime@1.1.0
│ │ ├── cli-width@2.1.0
│ │ ├── figures@1.7.0
│ │ ├─┬ readline2@1.0.1
│ │ │ ├─┬ code-point-at@1.0.0
│ │ │ │ └── number-is-nan@1.0.0
│ │ │ ├── is-fullwidth-code-point@1.0.0
│ │ │ └── mute-stream@0.0.5
│ │ ├── run-async@0.1.0
│ │ ├── rx-lite@3.1.2
│ │ ├── string-width@1.0.1
│ │ └── through@2.3.8
│ ├─┬ is-my-json-valid@2.13.1
│ │ ├── generate-function@2.0.0
│ │ ├─┬ generate-object-property@1.2.0
│ │ │ └── is-property@1.0.2
│ │ ├── jsonpointer@2.0.0
│ │ └── xtend@4.0.1
│ ├─┬ is-resolvable@1.0.0
│ │ └── tryit@1.0.2
│ ├─┬ js-yaml@3.6.1
│ │ ├─┬ argparse@1.0.7
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@2.7.2
│ ├─┬ json-stable-stringify@1.0.1
│ │ └── jsonify@0.0.0
│ ├─┬ levn@0.3.0
│ │ ├── prelude-ls@1.1.2
│ │ └── type-check@0.3.2
│ ├── lodash@4.14.2
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ optionator@0.8.1
│ │ ├── deep-is@0.1.3
│ │ ├── fast-levenshtein@1.1.4
│ │ └── wordwrap@1.0.0
│ ├── path-is-inside@1.0.1
│ ├── pluralize@1.2.1
│ ├── progress@1.1.8
│ ├─┬ require-uncached@1.0.2
│ │ ├─┬ caller-path@0.1.0
│ │ │ └── callsites@0.2.0
│ │ └── resolve-from@1.0.1
│ ├── shelljs@0.6.1
│ ├── strip-bom@3.0.0
│ ├── strip-json-comments@1.0.4
│ ├─┬ table@3.7.8
│ │ ├── bluebird@3.4.1
│ │ ├── slice-ansi@0.0.4
│ │ ├── tv4@1.2.7
│ │ └── xregexp@3.1.1
│ ├── text-table@0.2.0
│ └─┬ user-home@2.0.0
│   └── os-homedir@1.0.1
├── eslint-config-loopwerk@4.1.0
├── marked@0.3.6
├─┬ minimize@2.0.0
│ ├── argh@0.1.4
│ ├── async@2.0.1
│ ├─┬ cli-color@1.1.0
│ │ ├── d@0.1.1
│ │ ├── es5-ext@0.10.12
│ │ ├── es6-iterator@2.0.0
│ │ ├─┬ memoizee@0.3.10
│ │ │ ├─┬ es6-weak-map@0.1.4
│ │ │ │ ├── es6-iterator@0.1.3
│ │ │ │ └── es6-symbol@2.0.1
│ │ │ ├── lru-queue@0.1.0
│ │ │ └── next-tick@0.2.2
│ │ └── timers-ext@0.1.0
│ ├─┬ diagnostics@1.0.1
│ │ ├─┬ colorspace@1.0.1
│ │ │ ├─┬ color@0.8.0
│ │ │ │ ├── color-convert@0.5.3
│ │ │ │ └─┬ color-string@0.3.0
│ │ │ │   └── color-name@1.1.1
│ │ │ └── text-hex@0.0.0
│ │ ├─┬ enabled@1.0.2
│ │ │ └── env-variable@0.0.3
│ │ └─┬ kuler@0.0.0
│ │   └── colornames@0.0.2
│ ├── emits@3.0.0
│ ├─┬ htmlparser2@3.9.1
│ │ ├── domelementtype@1.3.0
│ │ ├── domhandler@2.3.0
│ │ ├─┬ domutils@1.5.1
│ │ │ └─┬ dom-serializer@0.1.0
│ │ │   └── domelementtype@1.1.3
│ │ ├── entities@1.1.1
│ │ └─┬ readable-stream@2.1.4
│ │   └── buffer-shims@1.0.0
│ └── node-uuid@1.4.7
├─┬ nunjucks@2.4.2
│ ├── asap@2.0.4
│ ├─┬ chokidar@1.6.0
│ │ ├─┬ anymatch@1.3.0
│ │ │ ├── arrify@1.0.1
│ │ │ └─┬ micromatch@2.3.11
│ │ │   ├─┬ arr-diff@2.0.0
│ │ │   │ └── arr-flatten@1.0.1
│ │ │   ├── array-unique@0.2.1
│ │ │   ├─┬ braces@1.8.5
│ │ │   │ ├─┬ expand-range@1.8.2
│ │ │   │ │ └─┬ fill-range@2.2.3
│ │ │   │ │   ├── is-number@2.1.0
│ │ │   │ │   ├── isobject@2.1.0
│ │ │   │ │   ├── randomatic@1.1.5
│ │ │   │ │   └── repeat-string@1.5.4
│ │ │   │ ├── preserve@0.2.0
│ │ │   │ └── repeat-element@1.1.2
│ │ │   ├─┬ expand-brackets@0.1.5
│ │ │   │ └── is-posix-bracket@0.1.1
│ │ │   ├── extglob@0.3.2
│ │ │   ├── filename-regex@2.0.0
│ │ │   ├─┬ kind-of@3.0.4
│ │ │   │ └── is-buffer@1.1.4
│ │ │   ├── normalize-path@2.0.1
│ │ │   ├─┬ object.omit@2.0.0
│ │ │   │ ├─┬ for-own@0.1.4
│ │ │   │ │ └── for-in@0.1.5
│ │ │   │ └── is-extendable@0.1.1
│ │ │   ├─┬ parse-glob@3.0.4
│ │ │   │ ├── glob-base@0.3.0
│ │ │   │ └── is-dotfile@1.0.2
│ │ │   └─┬ regex-cache@0.4.3
│ │ │     ├── is-equal-shallow@0.1.3
│ │ │     └── is-primitive@2.0.0
│ │ ├── async-each@1.0.0
│ │ ├─┬ fsevents@1.0.14
│ │ │ ├── nan@2.4.0
│ │ │ └─┬ node-pre-gyp@0.6.29
│ │ │   ├─┬ mkdirp@0.5.1
│ │ │   │ └── minimist@0.0.8
│ │ │   ├─┬ nopt@3.0.6
│ │ │   │ └── abbrev@1.0.9
│ │ │   ├─┬ npmlog@3.1.2
│ │ │   │ ├─┬ are-we-there-yet@1.1.2
│ │ │   │ │ └── delegates@1.0.0
│ │ │   │ ├── console-control-strings@1.1.0
│ │ │   │ ├─┬ gauge@2.6.0
│ │ │   │ │ ├── aproba@1.0.4
│ │ │   │ │ ├── has-color@0.1.7
│ │ │   │ │ ├── has-unicode@2.0.1
│ │ │   │ │ ├── object-assign@4.1.0
│ │ │   │ │ ├── signal-exit@3.0.0
│ │ │   │ │ ├─┬ string-width@1.0.1
│ │ │   │ │ │ ├─┬ code-point-at@1.0.0
│ │ │   │ │ │ │ └── number-is-nan@1.0.0
│ │ │   │ │ │ └── is-fullwidth-code-point@1.0.0
│ │ │   │ │ ├─┬ strip-ansi@3.0.1
│ │ │   │ │ │ └── ansi-regex@2.0.0
│ │ │   │ │ └── wide-align@1.1.0
│ │ │   │ └── set-blocking@2.0.0
│ │ │   ├─┬ rc@1.1.6
│ │ │   │ ├── deep-extend@0.4.1
│ │ │   │ ├── ini@1.3.4
│ │ │   │ ├── minimist@1.2.0
│ │ │   │ └── strip-json-comments@1.0.4
│ │ │   ├─┬ request@2.73.0
│ │ │   │ ├── aws-sign2@0.6.0
│ │ │   │ ├── aws4@1.4.1
│ │ │   │ ├─┬ bl@1.1.2
│ │ │   │ │ └── readable-stream@2.0.6
│ │ │   │ ├── caseless@0.11.0
│ │ │   │ ├─┬ combined-stream@1.0.5
│ │ │   │ │ └── delayed-stream@1.0.0
│ │ │   │ ├── extend@3.0.0
│ │ │   │ ├── forever-agent@0.6.1
│ │ │   │ ├─┬ form-data@1.0.0-rc4
│ │ │   │ │ └── async@1.5.2
│ │ │   │ ├─┬ har-validator@2.0.6
│ │ │   │ │ ├─┬ chalk@1.1.3
│ │ │   │ │ │ ├── ansi-styles@2.2.1
│ │ │   │ │ │ ├── escape-string-regexp@1.0.5
│ │ │   │ │ │ ├── has-ansi@2.0.0
│ │ │   │ │ │ └── supports-color@2.0.0
│ │ │   │ │ ├─┬ commander@2.9.0
│ │ │   │ │ │ └── graceful-readlink@1.0.1
│ │ │   │ │ ├─┬ is-my-json-valid@2.13.1
│ │ │   │ │ │ ├── generate-function@2.0.0
│ │ │   │ │ │ ├─┬ generate-object-property@1.2.0
│ │ │   │ │ │ │ └── is-property@1.0.2
│ │ │   │ │ │ ├── jsonpointer@2.0.0
│ │ │   │ │ │ └── xtend@4.0.1
│ │ │   │ │ └─┬ pinkie-promise@2.0.1
│ │ │   │ │   └── pinkie@2.0.4
│ │ │   │ ├─┬ hawk@3.1.3
│ │ │   │ │ ├── boom@2.10.1
│ │ │   │ │ ├── cryptiles@2.0.5
│ │ │   │ │ ├── hoek@2.16.3
│ │ │   │ │ └── sntp@1.0.9
│ │ │   │ ├─┬ http-signature@1.1.1
│ │ │   │ │ ├── assert-plus@0.2.0
│ │ │   │ │ ├─┬ jsprim@1.3.0
│ │ │   │ │ │ ├── extsprintf@1.0.2
│ │ │   │ │ │ ├── json-schema@0.2.2
│ │ │   │ │ │ └── verror@1.3.6
│ │ │   │ │ └─┬ sshpk@1.8.3
│ │ │   │ │   ├── asn1@0.2.3
│ │ │   │ │   ├── assert-plus@1.0.0
│ │ │   │ │   ├─┬ dashdash@1.14.0
│ │ │   │ │   │ └── assert-plus@1.0.0
│ │ │   │ │   ├── ecc-jsbn@0.1.1
│ │ │   │ │   ├─┬ getpass@0.1.6
│ │ │   │ │   │ └── assert-plus@1.0.0
│ │ │   │ │   ├── jodid25519@1.0.2
│ │ │   │ │   ├── jsbn@0.1.0
│ │ │   │ │   └── tweetnacl@0.13.3
│ │ │   │ ├── is-typedarray@1.0.0
│ │ │   │ ├── isstream@0.1.2
│ │ │   │ ├── json-stringify-safe@5.0.1
│ │ │   │ ├─┬ mime-types@2.1.11
│ │ │   │ │ └── mime-db@1.23.0
│ │ │   │ ├── node-uuid@1.4.7
│ │ │   │ ├── oauth-sign@0.8.2
│ │ │   │ ├── qs@6.2.0
│ │ │   │ ├── stringstream@0.0.5
│ │ │   │ ├── tough-cookie@2.2.2
│ │ │   │ └── tunnel-agent@0.4.3
│ │ │   ├─┬ rimraf@2.5.3
│ │ │   │ └─┬ glob@7.0.5
│ │ │   │   ├── fs.realpath@1.0.0
│ │ │   │   ├── inflight@1.0.5
│ │ │   │   ├─┬ minimatch@3.0.2
│ │ │   │   │ └─┬ brace-expansion@1.1.5
│ │ │   │   │   ├── balanced-match@0.4.2
│ │ │   │   │   └── concat-map@0.0.1
│ │ │   │   └── path-is-absolute@1.0.0
│ │ │   ├── semver@5.2.0
│ │ │   ├─┬ tar@2.2.1
│ │ │   │ ├── block-stream@0.0.9
│ │ │   │ ├─┬ fstream@1.0.10
│ │ │   │ │ └── graceful-fs@4.1.4
│ │ │   │ └── inherits@2.0.1
│ │ │   └─┬ tar-pack@3.1.4
│ │ │     ├─┬ debug@2.2.0
│ │ │     │ └── ms@0.7.1
│ │ │     ├── fstream-ignore@1.0.5
│ │ │     ├─┬ once@1.3.3
│ │ │     │ └── wrappy@1.0.2
│ │ │     ├─┬ readable-stream@2.1.4
│ │ │     │ ├── buffer-shims@1.0.0
│ │ │     │ ├── core-util-is@1.0.2
│ │ │     │ ├── isarray@1.0.0
│ │ │     │ ├── process-nextick-args@1.0.7
│ │ │     │ ├── string_decoder@0.10.31
│ │ │     │ └── util-deprecate@1.0.2
│ │ │     └── uid-number@0.0.6
│ │ ├── glob-parent@2.0.0
│ │ ├─┬ is-binary-path@1.0.1
│ │ │ └── binary-extensions@1.5.0
│ │ ├─┬ is-glob@2.0.1
│ │ │ └── is-extglob@1.0.0
│ │ └─┬ readdirp@2.1.0
│ │   └── set-immediate-shim@1.0.1
│ └─┬ yargs@3.32.0
│   ├── camelcase@2.1.1
│   ├─┬ cliui@3.2.0
│   │ └── wrap-ansi@2.0.0
│   ├── decamelize@1.2.0
│   ├─┬ os-locale@1.4.0
│   │ └─┬ lcid@1.0.0
│   │   └── invert-kv@1.0.0
│   ├── window-size@0.1.4
│   └── y18n@3.2.1
├── nunjucks-markdown@2.0.0
├─┬ raml-jsonschema-expander@1.1.0
│ └─┬ urllib-sync@1.1.3
│   ├─┬ urllib@2.9.1
│   │ ├── any-promise@1.2.0
│   │ ├─┬ default-user-agent@1.0.0
│   │ │ └─┬ os-name@1.0.3
│   │ │   ├─┬ osx-release@1.1.0
│   │ │   │ └── minimist@1.2.0
│   │ │   └─┬ win-release@1.1.1
│   │ │     └── semver@5.3.0
│   │ ├─┬ digest-header@0.0.1
│   │ │ └─┬ utility@0.1.11
│   │ │   └── address@1.0.0
│   │ ├── humanize-ms@1.0.2
│   │ ├── iconv-lite@0.4.13
│   │ ├── media-typer@0.3.0
│   │ └── statuses@1.2.1
│   └─┬ utility@1.7.1
│     ├── copy-to@2.0.1
│     └── escape-html@1.0.3
└─┬ raml2obj@3.0.0-beta1
  └─┬ raml-parser@0.8.18
    ├─┬ got@2.4.0
    │ ├─┬ duplexify@3.4.5
    │ │ ├── end-of-stream@1.0.0
    │ │ └── stream-shift@1.0.0
    │ ├── infinity-agent@1.0.2
    │ ├── is-stream@1.1.0
    │ ├── lowercase-keys@1.0.0
    │ ├── object-assign@2.1.1
    │ ├── prepend-http@1.0.4
    │ ├── read-all-stream@1.0.2
    │ └── timed-out@2.0.0
    ├── jju@1.2.1
    ├─┬ json-schema-ref-parser@3.1.2
    │ ├── call-me-maybe@1.0.1
    │ ├── es6-promise@3.2.1
    │ ├── ono@2.2.1
    │ └─┬ z-schema@3.17.0
    │   ├── lodash.get@4.4.1
    │   ├─┬ request@2.74.0
    │   │ ├── aws-sign2@0.6.0
    │   │ ├── aws4@1.4.1
    │   │ ├─┬ bl@1.1.2
    │   │ │ └── readable-stream@2.0.6
    │   │ ├── caseless@0.11.0
    │   │ ├─┬ combined-stream@1.0.5
    │   │ │ └── delayed-stream@1.0.0
    │   │ ├── extend@3.0.0
    │   │ ├── forever-agent@0.6.1
    │   │ ├─┬ form-data@1.0.0-rc4
    │   │ │ └── async@1.5.2
    │   │ ├── har-validator@2.0.6
    │   │ ├─┬ hawk@3.1.3
    │   │ │ ├── boom@2.10.1
    │   │ │ ├── cryptiles@2.0.5
    │   │ │ ├── hoek@2.16.3
    │   │ │ └── sntp@1.0.9
    │   │ ├─┬ http-signature@1.1.1
    │   │ │ ├── assert-plus@0.2.0
    │   │ │ ├─┬ jsprim@1.3.0
    │   │ │ │ ├── extsprintf@1.0.2
    │   │ │ │ ├── json-schema@0.2.2
    │   │ │ │ └── verror@1.3.6
    │   │ │ └─┬ sshpk@1.9.2
    │   │ │   ├── asn1@0.2.3
    │   │ │   ├── assert-plus@1.0.0
    │   │ │   ├─┬ dashdash@1.14.0
    │   │ │   │ └── assert-plus@1.0.0
    │   │ │   ├── ecc-jsbn@0.1.1
    │   │ │   ├─┬ getpass@0.1.6
    │   │ │   │ └── assert-plus@1.0.0
    │   │ │   ├── jodid25519@1.0.2
    │   │ │   ├── jsbn@0.1.0
    │   │ │   └── tweetnacl@0.13.3
    │   │ ├── is-typedarray@1.0.0
    │   │ ├── isstream@0.1.2
    │   │ ├── json-stringify-safe@5.0.1
    │   │ ├─┬ mime-types@2.1.11
    │   │ │ └── mime-db@1.23.0
    │   │ ├── oauth-sign@0.8.2
    │   │ ├── qs@6.2.1
    │   │ ├── stringstream@0.0.5
    │   │ ├── tough-cookie@2.3.1
    │   │ └── tunnel-agent@0.4.3
    │   └── validator@5.5.0
    ├── pluralize@1.1.6
    ├── q@0.9.7
    └── uritemplate@0.3.4
```

**Comment by kevinrenskers** [comment]
Thanks! Taking a look right away.
