### ISSUE TITLE
Unhandled Parsing Error

### ISSUE THREAD

**Issue by carlosmsr** [raml2html/raml2html#264]
Given a format error like: 

```
  type: datetime
    description: agent or device
    timestamp when the point was measured
    required: false
```

the following line on `[..]\raml2html\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js` (ln. 521)

```
while (_issue.extras.length > 0)
```

generates this error message: 

```
TypeError: Cannot read property 'length' of undefined
    at Object.validate ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:521:49)
    at ASTNodeImpl.validate ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:939:16)
    at [..]\raml2html\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:407:15
    at Array.forEach (native)
    at validateBasic ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:402:12)
    at Object.validate ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:599:13)
    at ASTNodeImpl.validate ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:939:16)
    at ASTNodeImpl.validate ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:932:24)
    at ASTNodeImpl.BasicASTNode.errors ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:157:14)
    at ApiImpl.BasicNodeImpl.errors ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\wrapped-ast\parserCore.js:204:42)
```

Probably checking for:

```
if(issue != null && issue.extras != null)
```

would fix it.

**Comment by kevinrenskers** [comment]
It seems that error comes from the `raml-1-parser` code, not raml2html.

**Comment by kevinrenskers** [comment]
https://github.com/raml-org/raml-js-parser-2/issues/496
