### ISSUE TITLE
Run `raml2html --help` got `SyntaxError: Unexpected token {`

### ISSUE THREAD

**Issue by lijinma** [raml2html/raml2html#285]
command:
```
$ raml2html --help
```

```
const { arraysToObjects, recursiveObjectToArray } = require('./arrays-objects-helpers');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/lijinma/test/node_modules/raml2html/index.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

I have no idea what's wrong with `{`;

My node version is : `v4.5.0`

Could you kindly help me ?

**Comment by lijinma** [comment]
I think is the node version issue.

**Comment by kevinrenskers** [comment]
Ah damn, yeah probably needs Node 6. I'll fix it so it runs on Node 4.

**Comment by lijinma** [comment]
@kevinrenskers Thanks, I update node to the latest version and it work. 💯

**Comment by kevinrenskers** [comment]
Okay great :) I've also fixed Node 4 support in the meantime for other users.
