### ISSUE TITLE
template render error

### ISSUE THREAD

**Issue by ahmeddaif** [raml2html/raml2html#305]
when use type array in body i get template render error

**Comment by kevinrenskers** [comment]
Can you supply a minimal example RAML file?

**Comment by ahmeddaif** [comment]
post:
  description: add new service
  body:
    application/json:
      type: object
      properties:
        car_types:
          type: array
          required: true
          description: array of related car types (required when service with_car_type attribue = 1)
      example: |
        {
          "car_types":[2,3],
        }

**Comment by nickburns2006** [comment]
I seem to be getting this as well...

**Comment by kevinrenskers** [comment]
Are you getting an actual template render error or a parser error? Parse errors have nothing to do with raml2html (see also the readme of this project). I'm asking because with this particular example RAML document, it doesn't contain valid JSON; see that dangling comma. When I removed that comma I got the following template render error:

```
error!  { Template render error: (/Users/kevin/Workspace/raml2html/lib/template.nunjucks)
  Template render error: (/Users/kevin/Workspace/raml2html/lib/template.nunjucks)
  Template render error: (/Users/kevin/Workspace/raml2html/lib/resource.nunjucks) [Line 166, Column 44]
  Template render error: (/Users/kevin/Workspace/raml2html/lib/template.nunjucks)
  Template render error: (/Users/kevin/Workspace/raml2html/lib/resource.nunjucks)
  Template render error: (/Users/kevin/Workspace/raml2html/lib/item.nunjucks) [Line 15, Column 37]
  TypeError: Cannot read property 'indexOf' of undefined
    at Object.exports.prettifyError (/Users/kevin/Workspace/raml2html/node_modules/nunjucks/src/lib.js:34:15)
    at /Users/kevin/Workspace/raml2html/node_modules/nunjucks/src/environment.js:486:31
    at new_cls.root [as rootRenderFunc] (eval at _compile (/Users/kevin/Workspace/raml2html/node_modules/nunjucks/src/environment.js:565:24), <anonymous>:191:3)
    at new_cls.render (/Users/kevin/Workspace/raml2html/node_modules/nunjucks/src/environment.js:479:15)
    at /Users/kevin/Workspace/raml2html/node_modules/nunjucks/src/environment.js:312:35
    at createTemplate (/Users/kevin/Workspace/raml2html/node_modules/nunjucks/src/environment.js:234:25)
    at handle (/Users/kevin/Workspace/raml2html/node_modules/nunjucks/src/environment.js:249:25)
    at /Users/kevin/Workspace/raml2html/node_modules/nunjucks/src/environment.js:263:21
    at next (/Users/kevin/Workspace/raml2html/node_modules/nunjucks/src/lib.js:207:13)
    at Object.exports.asyncIter (/Users/kevin/Workspace/raml2html/node_modules/nunjucks/src/lib.js:214:5) name: 'Template render error' }
```

Please, next time when you submit a bug report, include the actual error message and a working RAML file to reproduce it with.

**Comment by kevinrenskers** [comment]
That said, thanks for reporting it though :) 4.0.6 just got published with a fix.
